spring:
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: HTML
    cache: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
server:
  port: 8080